#
# general node-wide settings
#


node_name: telos-evm-local-tea
node_type: local

data_dir: '{{ playbook_dir }}/data'
logs_dir: '{{ playbook_dir }}/logs'


#
# per service configs
#


reth:
  name: '{{ node_name }}-reth'
  image: telos-evm:reth-telos-1.0.0

  log_level: info
  log_file: reth.log

  chain: tevmtestnet

  rpc_port: 9545
  ws_port: 9546
  auth_rpc_port: 9551
  discovery_port: 40303

  sign_account: rpc.evm
  sign_permission: rpc
  sign_key: 5KjZqM5UTGmmHByRXZaDM1a5JupgGM9925H3NEroTr6CdEZQDvH


tcc:
  name: '{{ node_name }}-tcc'
  image: telos-evm:tcc-1.0.0

  log_level: info
  log_file: tcc.log

  chain_id: 41
  batch_size: 1
  prev_hash: b25034033c9ca7a40e879ddcc29cf69071a22df06688b5fe8cc2d68b4e0528f9
  start_block: 1
  block_checkpoint_interval: 1000
  maximum_sync_range: 100000
  latest_blocks_in_db_num: 500


leap:
  name: '{{ node_name }}-leap'
  image: telos-evm:leap-5.0.3

  log_file: leap.log

  # run cmd
  binary: nodeos

  genesis: local.json

  use_resource_monitor: true
  is_producer: true
  evm_contract: eosio.evm/regular

  skip_init: false

  chain_id: 5ef798208828ef4385a9f605066204cc3fb83e33146d868440283d8687a4b0ee

  ini:
    agent_name: Telos Sample Node

    # network
    http_host: 127.0.0.1
    http_port: 8888

    ship_host: 127.0.0.1
    ship_port: 29999

    p2p_host: 127.0.0.1
    p2p_port: 9876

    allow_origin: "*"
    http_validate_host: false
    http_verbose_error: true
    http_max_body_size: 100000000
    http_max_response_time: 100000
    sync_fetch_span: 2000
    max_clients: 250
    p2p_max_nodes: 1
    cleanup_period: 30
    allowed_connection: any

    # runtime
    wasm_runtime: eos-vm-jit
    vm_oc_compile_threads: 4
    vm_oc_enable: true
    read_window_time: 2000000
    chain_state_size: 65536
    abi_serializer_max_time: 2000000
    disable_subjective_billing: true
    max_transaction_time: 500

    # api
    account_queries: true
    contracts_console: true
    trace_history: true
    chain_history: true
    history_debug_mode: true
    history_dir: state-history
    sig_provider: EOS5GnobZ231eekYUJHGTcmy2qve1K23r5jSFQbMfwWTtPB7mFZ1L=KEY:5Jr65kdYmn33C3UabzhmWDm2PuqbRfPuDStts3ZFNSBLM7TqaiL
    enable_stale_production: true

    # plugins
    plugins:
      - eosio::http_plugin
      - eosio::chain_api_plugin
      - eosio::chain_plugin
      - eosio::net_plugin
      - eosio::producer_plugin
      - eosio::producer_api_plugin
      - eosio::state_history_plugin
