#
# general node-wide settings
#


node_name: telos-evm-testnet-tea
node_type: testnet

data_dir: '{{ playbook_dir }}/data'
logs_dir: '{{ playbook_dir }}/logs'


#
# per service configs
#


reth:
  name: '{{ node_name }}-reth'
  image: telos-evm:reth-telos-1.0.0

  log_level: info
  log_file: reth.log

  chain: tevmtestnet

  rpc_port: 9545
  ws_port: 9546
  auth_rpc_port: 9551
  discovery_port: 40303

  sign_account: rpc.evm
  sign_permission: rpc
  sign_key: 5KjZqM5UTGmmHByRXZaDM1a5JupgGM9925H3NEroTr6CdEZQDvH


tcc:
  name: '{{ node_name }}-tcc'
  image: telos-evm:tcc-1.0.0

  log_level: info
  log_file: tcc.log

  chain_id: 41
  batch_size: 500
  prev_hash: b25034033c9ca7a40e879ddcc29cf69071a22df06688b5fe8cc2d68b4e0528f9
  start_block: 1
  block_checkpoint_interval: 1000
  maximum_sync_range: 100000
  latest_blocks_in_db_num: 500


leap:
  name: '{{ node_name }}-leap'
  image: telos-evm:leap-5.0.3

  log_file: leap.log

  # run cmd
  binary: nodeos

  genesis: testnet.json
  snapshot: /telos-testnet-snapshot-evm-deploy.bin

  use_resource_monitor: true

  chain_id: 1eaa0824707c8c16bd25145493bf062aecddfeb56c736f6ba6397f3195f33c9f

  ini:
    agent_name: Telos Sample Node

    # network
    http_host: 127.0.0.1
    http_port: 8888

    ship_host: 127.0.0.1
    ship_port: 29999

    p2p_host: 127.0.0.1
    p2p_port: 9876

    allow_origin: "*"
    http_validate_host: false
    http_verbose_error: true
    http_max_response_time: 100000
    sync_fetch_span: 2000
    max_clients: 250

    # runtime
    wasm_runtime: eos-vm-jit
    vm_oc_compile_threads: 4
    vm_oc_enable: true
    read_window_time: 2000000
    chain_state_size: 65536
    abi_serializer_max_time: 2000000
    disable_subjective_billing: true
    max_transaction_time: 500

    # api
    account_queries: true
    contracts_console: true
    trace_history: true
    chain_history: true
    history_debug_mode: true
    history_dir: state-history

    # plugins
    plugins:
      - eosio::http_plugin
      - eosio::chain_api_plugin
      - eosio::state_history_plugin

    peers:
      - testnet2.telos.eosusa.news:59877
      - node1.testnet.telosglobal.io:9876
      - basho.eos.barcelona:9899
      - sslapi.teloscentral.com:9875
      - 145.239.133.188:5566
      - testnet.telos.eclipse24.io:6789
      - p2p.telos.testnet.detroitledger.tech:30001
      - basho-p2p.telosuk.io:19876
      - telos-testnet.atticlab.net:7876
      - testnet.eossweden.eu:8022
      - testnet.telos.cryptosuvi.io:2223
      - p2p-test.tlos.goodblock.io:9876
      - telosapi.eosmetal.io:59877
      - 207.148.6.75:9877
      - telosgermany-testnet.genereos.io:9876
      - 176.9.86.214:9877
      - peer1-telos-testnet.eosphere.io:9876
      - testnet.telos.africa:9875
      - p2p.testnet.telosgreen.com:9876
      - testnet2p2p.telosarabia.net:9876
      - 157.230.29.117:9876
      - test.telos.kitchen:9876
      - prod.testnet.bp.teleology.world:9876
      - telos-testnet.eoscafeblock.com:9879
      - p2p.basho.telos.dutcheos.io:7654
      - testnet-b.telos-21zephyr.com:9876
      - p2p.testnet.telosunlimited.io:9876
      - peer.tlostest.alohaeos.com:9876
      - 52.175.222.202:9877
      - testnet2.telos.eosindex.io:9876
      - basho.sofos.network:9876
      - 85.152.18.129:39876
      - telostestnet.ikuwara.com:9876
      - p2p.testnet.nytelos.com:8012
      - telos.basho.eosdublin.io:9876
      - telos-testnet.cryptolions.io:9871
      - api.basho.eostribe.io:9880
      - p2p-telos-testnet.hkeos.com:59876
      - t-seed.teloskorea.com:19876
      - telos.testnet.boid.animus.is:3535
      - telos.testnet.boid.animus.is:5050
      - kandaweather-testnet.ddns.net:8765
      - telos-testnet.eosio.cr:9879
      - testnet.dailytelos.net:9877
      - testnet.telos.goodblock.io:9876
