#
# general node-wide settings
#


node_name: telos-evm-mainnet-tea
node_type: mainnet

data_dir: '{{ playbook_dir }}/data'
logs_dir: '{{ playbook_dir }}/logs'


#
# per service configs
#


reth:
  name: '{{ node_name }}-reth'
  image: telos-evm:reth-telos-1.0.0

  log_level: info
  log_file: reth.log

  chain: tevmmainnet

  rpc_port: 9545
  ws_port: 9546
  auth_rpc_port: 9551
  discovery_port: 40303

  sign_account: rpc.evm
  sign_permission: rpc
  sign_key: 5KjZqM5UTGmmHByRXZaDM1a5JupgGM9925H3NEroTr6CdEZQDvH


tcc:
  name: '{{ node_name }}-tcc'
  image: telos-evm:tcc-1.0.0

  log_level: info
  log_file: tcc.log

  chain_id: 40
  batch_size: 500
  prev_hash: 36fe7024b760365e3970b7b403e161811c1e626edd68460272fcdfa276272563
  start_block: 1
  block_checkpoint_interval: 1000
  maximum_sync_range: 100000
  latest_blocks_in_db_num: 500


leap:
  name: '{{ node_name }}-leap'
  image: telos-evm:leap-5.0.3

  log_file: leap.log

  # run cmd
  binary: nodeos

  genesis: mainnet.json
  # snapshot: /telos-mainnet-snapshot-evm-deploy.bin

  use_resource_monitor: true
  is_producer: false

  skip_init: true

  chain_id: 4667b205c6838ef70ff7988f6e8257e8be0e1284a2f59699054a018f743b1d11

  ini:
    agent_name: Telos Sample Node

    # network
    http_host: 127.0.0.1
    http_port: 8888

    ship_host: 127.0.0.1
    ship_port: 29999

    p2p_host: 127.0.0.1
    p2p_port: 9876

    allow_origin: "*"
    http_validate_host: false
    http_verbose_error: true
    http_max_response_time: 100000
    sync_fetch_span: 2000
    max_clients: 250

    # runtime
    wasm_runtime: eos-vm-jit
    vm_oc_compile_threads: 4
    vm_oc_enable: true
    read_window_time: 2000000
    chain_state_size: 65536
    abi_serializer_max_time: 2000000
    disable_subjective_billing: true
    max_transaction_time: 500

    # api
    account_queries: true
    contracts_console: true
    trace_history: true
    chain_history: true
    history_debug_mode: true
    history_dir: state-history

    # plugins
    plugins:
      - eosio::http_plugin
      - eosio::chain_api_plugin
      - eosio::state_history_plugin

    peers:
      - telosp2p.actifit.io:9876
      - telos.eu.eosamsterdam.net:9120
      - p2p.telos.eosargentina.io:9879
      - telos.p2p.boid.animus.is:5151
      - telos.p2p.boid.animus.is:5252
      - p2p.telos.y-knot.io:9877
      - telos.caleos.io:9880
      - p2p.creativblock.org:9876
      - p2p.telos.cryptobloks.io:9876
      - telos.cryptolions.io:9871
      - p2p.dailytelos.net:9876
      - p2p.telos.detroitledger.tech:1337
      - node-telos.eosauthority.com:10311
      - telosp2p.eos.barcelona:2095
      - peer1-telos.eosphere.io:9876
      - peer2-telos.eosphere.io:9876
      - telos.eosrio.io:8092
      - api.telos.cryptotribe.io:7876
      - telos.p2p.eosusa.io:9876
      - telos.eosvenezuela.io:9871
      - p2p.fortisbp.io:9876
      - mainnet.telos.goodblock.io:9879
      - seed-telos.infinitybloc.io:9877
      - p2p.kainosbp.com:9876
      - kandaweather-mainnet.ddns.net:9876
      - tlos-p2p.katalyo.com:11877
      - telos.seed.eosnation.io:9876
      - p2p.telos.nodenode.org:9876
      - p2p.telos.pandabloks.com:9876
      - mainnet.persiantelos.com:8880
      - telosp2p.sentnl.io:4242
      - p2p.telos.africa:9877
      - telos.eossweden.eu:8012
      - telos.greymass.com:19871
      - peers.teleology.one:9876
      - telos.teleology.one:9876
      - p2p.telosarabia.net:9876
      - sslapi.teloscentral.com:9876
      - testnet.telosculture.com:9874
      - p2p.telosgermany.genereos.io:9876
      - node1.us-east.telosglobal.io:9876
      - node1.us-west.telosglobal.io:9876
      - p2p2.telos.telosgreen.com:9877
      - p2p.telos.blocksindia.com:9876
      - api.telos.kitchen:9876
      - seed.teloskorea.com:9876
      - seed.telosmadrid.io:9877
      - p2p.telosuk.io:9876
      - p2p.telosunlimited.io:9876
      - telosyouth.io:9876
      - p2p.theteloscope.io:9876
      - mainnet.teloscrew.com:18876
      - 136.243.90.53:9876
      - p2p.telos.dutcheos.io:9876
      - p2p.telos.zenblocks.io:9876
