#
# general node-wide settings
#


node_name: telos-evm-local-tea
node_type: local

data_dir: '{{ playbook_dir }}/data'
logs_dir: '{{ playbook_dir }}/logs'


#
# per service configs
#


redis:
  name: '{{ node_name }}-redis'
  image: redis:7

  host: 127.0.0.1
  port: 6379


es:
  name: '{{ node_name }}-elastic'
  image: telos-evm:es-8.13.4

  cluster_name: '{{ node_name }}_local_cluster'
  host: 127.0.0.1
  port: 9200
  transport_port: 9300


kibana:
  name: '{{ node_name }}-kibana'
  image: docker.elastic.co/kibana/kibana:8.13.4

  host: 127.0.0.1
  port: 5601


leap:
  name: '{{ node_name }}-leap'
  image: telos-evm:leap-4.0.6-subst

  log_file: leap.log

  # run cmd
  binary: nodeos

  genesis: local.json

  use_resource_monitor: true
  is_producer: true
  subst_admin_apis: true
  override_tx_time: 500

  skip_init: false
  evm_contract: 'eosio.evm/receiptless'

  # substitution
  subst_type: by-name
  subst_by_name: /root/contracts/eosio.evm/regular/regular.wasm
  subst_by_manifest: http://evmwasms.s3.amazonaws.com/subst.json

  chain_id: c4c5fcc7b6e5e7484eb6b609e755050ebba977c4c291a63aab42d94c0fb8c2cf

  ini:
    agent_name: Telos Sample Node

    # network
    http_host: 127.0.0.1
    http_port: 8888

    ship_host: 127.0.0.1
    ship_port: 29999

    p2p_host: 127.0.0.1
    p2p_port: 9876

    allow_origin: "*"
    http_validate_host: false
    http_verbose_error: true
    http_max_body_size: 100000000
    http_max_response_time: 100000
    sync_fetch_span: 2000
    max_clients: 250
    p2p_max_nodes: 1
    cleanup_period: 30
    allowed_connection: any

    # runtime
    wasm_runtime: eos-vm-jit
    vm_oc_compile_threads: 4
    vm_oc_enable: true
    read_window_time: 2000000
    chain_state_size: 65536
    abi_serializer_max_time: 2000000
    disable_subjective_billing: true
    max_transaction_time: 500

    # api
    account_queries: true
    contracts_console: true
    trace_history: true
    chain_history: true
    history_debug_mode: true
    history_dir: state-history
    sig_provider: EOS5GnobZ231eekYUJHGTcmy2qve1K23r5jSFQbMfwWTtPB7mFZ1L=KEY:5Jr65kdYmn33C3UabzhmWDm2PuqbRfPuDStts3ZFNSBLM7TqaiL
    enable_stale_production: true

    # plugins
    plugins:
      - eosio::http_plugin
      - eosio::chain_api_plugin
      - eosio::state_history_plugin
      - eosio::chain_plugin
      - eosio::net_plugin
      - eosio::producer_plugin
      - eosio::producer_api_plugin
      - eosio::state_history_plugin
      - eosio::subst_api_plugin


translator:
  name: '{{ node_name }}-translator'
  image: telos-evm:translator-1.1.0

  log_file: translator.log
  log_level: debug
  reader_log_level: info

  # network
  ws_host: 127.0.0.1
  ws_port: 7300

  chain_id: 41
  irreversible_only: 'false'

  start_block: 2
  stop_block: -1
  block_delta: 0
  # prev_hash:
  # validate_hash:

  # perf
  block_hist_size: 1800
  stall_counter: 5
  reader_workers: 1
  evm_workers: 4
  max_ws_payload: 2048

  es:
    dump_size: 1
    req_timeout: 480000
    docs_per_index: 10000000
    scroll_size: 6000
    scroll_window: 8s
    num_of_shards: 1
    num_of_replicas: 0
    refresh_interval: -1
    codec: best_compression
    suffix:
      delta: delta-v1.5
      transaction: action-v1.5
      error: error-v1.5
      fork: fork-v1.5


rpc:
  name: '{{ node_name }}-rpc'
  image: telos-evm:rpc-1.1.8

  log_file: rpc.log

  # network
  host: 127.0.0.1
  port: 7000

  ws_host: 127.0.0.1
  ws_port: 7400

  debug: 'true'

  signer_account: rpc.evm
  signer_permission: active
  signer_key: 5Jr65kdYmn33C3UabzhmWDm2PuqbRfPuDStts3ZFNSBLM7TqaiL
