---
- name: Telos EVM Node
  hosts: localhost
  become: yes

  environment:
    PYTHONPATH: "{{ lookup('env', 'PYTHONPATH') }}"

  vars_files:
    - config.yml

  tasks:
    - name: Check leap data directory existence
      stat:
        path: '{{ data_dir }}/leap/blocks/blocks.log'
      register: leap_data_dir

    - name: Generate dynamic vars
      set_fact:
          is_leap_relaunch: '{{ leap_data_dir.stat.exists }}'

          es_endpoint: 'http://127.0.0.1:{{ es.port }}'

          leap_http_addr: '{{ leap.ini.http_host }}:{{ leap.ini.http_port }}'
          leap_http_endpoint: 'http://127.0.0.1:{{ leap.ini.http_port }}'
          leap_ship_addr: '{{ leap.ini.ship_host }}:{{ leap.ini.ship_port }}'
          leap_ship_endpoint: 'ws://127.0.0.1:{{ leap.ini.ship_port }}'
          leap_p2p_addr: '{{ leap.ini.p2p_host }}:{{ leap.ini.p2p_port }}'

          translator_ws_uri: 'ws://127.0.0.1:{{ translator.ws_port }}/evm'

          leap_remote_endpoint: >-
              {% if node_type == 'local' %}
                'http://127.0.0.1:{{ leap.ini.http_port }}'
              {% elif node_type == 'mainnet' %}
                'http://mainnet.telos.net'
              {% elif node_type == 'testnet' %}
                'http://testnet.telos.net'
              {% else %}
                undefined
              {% endif %}

    - name: Create configs directory
      file:
        path: configs
        state: directory

    - name: Ensure data directory exists
      file:
        path: '{{ item }}'
        state: directory
      with_items:
        - '{{ data_dir }}'
        - '{{ data_dir }}/es'
        - '{{ data_dir }}/leap'
        - '{{ logs_dir }}'

    - name: Check if Docker is installed
      command: docker --version
      register: docker_installed
      ignore_errors: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes
      when: docker_installed.rc != 0

    - name: Ensure redis service is up
      include_tasks: playbooks/start/redis.yml

    - name: Ensure elastic service is up
      include_tasks: playbooks/start/elastic.yml

    - name: Ensure leap service is up
      include_tasks: playbooks/start/leap.yml

    - name: Ensure translator service is up
      include_tasks: playbooks/start/translator.yml

    - name: Ensure rpc service is up
      include_tasks: playbooks/start/rpc.yml

