---
- name: Stop Telos EVM Node
  hosts: localhost
  vars_files:
    - config.yml
  tasks:
    - name: Stop Docker containers with specific signals
      docker_container:
        name: '{{ item.name }}'
        stop_signal: '{{ item.signal }}'
        state: stopped
        timeout: 120
      with_items:
        - { name: '{{ es.name }}', signal: 'SIGTERM' }
        - { name: '{{ kibana.name }}', signal: 'SIGTERM' }
        - { name: '{{ redis.name }}', signal: 'SIGQUIT' }
        - { name: '{{ leap.name }}', signal: 'SIGINT' }
        - { name: '{{ translator.name }}', signal: 'SIGINT' }
        - { name: '{{ rpc.name }}', signal: 'SIGKILL' }

