---
- name: Stop Telos EVM Node
  hosts: localhost
  vars_files:
    - config.yml
  tasks:
    - name: Stop Docker containers with specific signals
      docker_container:
        name: '{{ item.name }}'
        stop_signal: '{{ item.signal }}'
        state: stopped
        timeout: 120
      with_items:
        - { name: '{{ tcc.name }}', signal: 'SIGINT' }
        - { name: '{{ reth.name }}', signal: 'SIGINT' }
        - { name: '{{ leap.name }}', signal: 'SIGINT' }

